# Generated by Django 3.1.3 on 2020-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Desciption')),
                ('project_link', models.CharField(max_length=500, verbose_name='Project Link')),
                ('project_blog', models.CharField(max_length=500, verbose_name='Project Blog')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
    ]
