# Generated by Django 3.1.3 on 2020-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbie', models.CharField(max_length=100, verbose_name='Hobbie Name')),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
    ]
