# Generated by Django 3.1.3 on 2020-11-09 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Blog Post Name')),
                ('discription', models.TextField(verbose_name='Description')),
                ('post_link', models.CharField(max_length=500, verbose_name='Blog Post Link')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Post Date')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
