# Generated by Django 3.1.3 on 2020-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Course Name')),
                ('discription', models.TextField(verbose_name='Description')),
                ('from_date', models.DateField(verbose_name='Start Date')),
                ('to_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
