# Generated by Django 3.1.3 on 2020-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=500, verbose_name='Degree Name')),
                ('college', models.CharField(max_length=500, verbose_name='College Name')),
                ('sgpa', models.CharField(max_length=500, verbose_name='SGPA / Percentage')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('location', models.CharField(max_length=500, verbose_name='Loacation')),
            ],
            options={
                'verbose_name_plural': 'Achivements',
            },
        ),
    ]
