# Generated by Django 3.1.3 on 2020-11-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=500, verbose_name='Link Display Name')),
                ('link_url', models.CharField(max_length=500, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='NavTabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=500, verbose_name='Nav Display Name')),
                ('nav_link', models.CharField(max_length=500, verbose_name='Nav Link')),
                ('nav_icon', models.CharField(max_length=500, verbose_name='Icon Tag')),
            ],
            options={
                'verbose_name_plural': 'Navigation Links',
            },
        ),
        migrations.RenameModel(
            old_name='Intro',
            new_name='Introduction',
        ),
        migrations.AlterModelOptions(
            name='introduction',
            options={'verbose_name_plural': 'Introduction (only one feild allowed)'},
        ),
    ]
