# Generated by Django 3.1.3 on 2020-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20201109_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pdf', models.FileField(upload_to='files/', verbose_name='PDF FILE')),
            ],
            options={
                'verbose_name_plural': 'PDF Resume (only one instance allowed)',
            },
        ),
    ]
