# Generated by Django 3.1.3 on 2020-11-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=500, verbose_name='Designation Name')),
                ('company', models.CharField(max_length=500, verbose_name='Company Name')),
                ('work', models.TextField(max_length=500, verbose_name='Describe Work You Did')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('location', models.CharField(max_length=500, verbose_name='Loacation')),
                ('certificate', models.FileField(upload_to='experiences/', verbose_name='Certificate')),
            ],
            options={
                'verbose_name_plural': 'Work Experience',
            },
        ),
    ]
